import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import {ClerkProvider, ClerkLoaded, ClerkLoading} from "@clerk/nextjs"
import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkLoading>
          <div className="fixed top-0 left-0 w-screen h-screen bg-background flex justify-center items-center">
            <p className="text-2xl font-bold text-white">Loading</p>
          </div>
        </ClerkLoading>
        <ClerkLoaded>
          <main className="flex flex-col min-h-[calc(100vh-111px)]">
            <Header/>
            <div className="flex-1 flex flex-col h-full">{children}</div>
            <Footer/>
          </main>
          <Toaster/>
        </ClerkLoaded>
      </body>
    </html>
    </ClerkProvider>
  );
}
